import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home:  Scaffold(
        body: ListView(children: [
          // Lỗi 2: Thay thế () bằng một widget hợp lệ
          HomePage(),
        ]),
      ),
    );
  }
}

// Lỗi 1: Thêm tên cho class, ví dụ: "HomePage"
class HomePage extends StatelessWidget {
  // Thêm constructor cho widget
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 375,
          height: 812,
          clipBehavior: Clip.antiAlias,
          decoration: const BoxDecoration(color: Color(0xFFD7E8FF)),
          child: Stack(
            children: [
              Positioned(
                left: -2,
                top: 0,
                child: Container(
                  width: 375,
                  height: 299,
                  decoration: const BoxDecoration(color: Color(0xFF1F3A60)),
                ),
              ),
              const Positioned(
                left: 21,
                top: 415,
                child: SizedBox(
                  width: 153,
                  child: Text(
                    'Thuốc phổ biến',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 20,
                      fontFamily: 'Open Sans',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 32.13,
                top: 111,
                child: SizedBox(
                  width: 147.75,
                  child: Text(
                    'Tìm kiếm',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 20,
                      fontFamily: 'Open Sans',
                      fontWeight: FontWeight.w300,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 161,
                top: 586,
                child: SizedBox(
                  width: 124,
                  child: Text(
                    'Thuốc nhỏ mắt VRohto ',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 10,
                      fontFamily: 'Open Sans',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 161,
                top: 454,
                child: Container(
                  width: 125,
                  height: 125,
                  decoration: ShapeDecoration(
                    image: const DecorationImage(
                      image: NetworkImage("https://placehold.co/125x125"),
                      fit: BoxFit.cover,
                    ),
                    shape: RoundedRectangleBorder(
                      side: const BorderSide(width: 1),
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 295,
                top: 586,
                child: SizedBox(
                  width: 124,
                  child: Text(
                    'Paracetamol Stada',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 10,
                      fontFamily: 'Open Sans',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 302,
                top: 454,
                child: Container(
                  width: 125,
                  height: 125,
                  decoration: ShapeDecoration(
                    image: const DecorationImage(
                      image: NetworkImage("https://placehold.co/125x125"),
                      fit: BoxFit.cover,
                    ),
                    shape: RoundedRectangleBorder(
                      side: const BorderSide(width: 1),
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 21,
                top: 177,
                child: Container(
                  width: 337,
                  height: 211,
                  decoration: ShapeDecoration(
                    image: const DecorationImage(
                      image: NetworkImage("https://placehold.co/337x211"),
                      fit: BoxFit.cover,
                    ),
                    shape: RoundedRectangleBorder(
                      side: const BorderSide(width: 1),
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 20,
                top: 586,
                child: SizedBox(
                  width: 124,
                  child: Text(
                    'Thuốc nhỏ mắt Systane ultra nhức mỏi mắt, khô mắt',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 10,
                      fontFamily: 'Open Sans',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 454,
                child: Container(
                  width: 125,
                  height: 125,
                  decoration: ShapeDecoration(
                    image: const DecorationImage(
                      image: NetworkImage("https://placehold.co/125x125"),
                      fit: BoxFit.cover,
                    ),
                    shape: RoundedRectangleBorder(
                      side: const BorderSide(width: 1),
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 280,
                top: 5,
                child: SizedBox(width: 30, height: 20, child: Stack()),
              ),
              Positioned(
                left: 310,
                top: 5,
                child: Container(
                  width: 20,
                  height: 20,
                  clipBehavior: Clip.antiAlias,
                  decoration: const BoxDecoration(),
                  child: Stack(),
                ),
              ),
              const Positioned(
                left: 24,
                top: 10,
                child: Text(
                  '10:23',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 12,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ),
              Positioned(
                left: 295,
                top: 101,
                child: Container(
                  width: 52,
                  height: 42,
                  decoration: const BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/52x42"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: -11,
                top: 721,
                child: Container(
                  width: 398,
                  height: 91,
                  decoration: const ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        bottomLeft: Radius.circular(24),
                        bottomRight: Radius.circular(24),
                      ),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 57,
                        child: Container(
                          width: 394,
                          height: 34,
                          clipBehavior: Clip.antiAlias,
                          decoration: const ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                bottomLeft: Radius.circular(24),
                                bottomRight: Radius.circular(24),
                              ),
                            ),
                          ),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 393,
                          height: 58,
                          child: Row(
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.end,
                            children: [
                              const Expanded(
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    SizedBox(
                                      width: 24,
                                      height: 24,
                                      // Lỗi 4: Sửa `withValues` thành `withOpacity`
                                      // Hoặc đơn giản là dùng `const` để mã sạch hơn
                                      child: Icon(Icons.home, color: Color(0xFFFF3B30)),
                                    ),
                                    // Lỗi 3: Thêm SizedBox để tạo khoảng cách
                                    SizedBox(height: 6),
                                    Text(
                                      'Trang Chủ ',
                                      style: TextStyle(
                                        color: Color(0xFFFF3B30),
                                        /* Colors-Red */
                                        fontSize: 12,
                                        fontFamily: 'Urbanist',
                                        fontWeight: FontWeight.w500,
                                        height: 1.25,
                                        letterSpacing: 0.24,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                              const Expanded(
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    // Thêm Icon cho nhất quán
                                    Icon(Icons.medical_services_outlined),
                                    // Lỗi 3: Thêm SizedBox để tạo khoảng cách
                                    SizedBox(height: 6),
                                    Text(
                                      'Thuốc ',
                                      style: TextStyle(
                                        color: Colors.black,
                                        fontSize: 12,
                                        fontFamily: 'Urbanist',
                                        fontWeight: FontWeight.w500,
                                        height: 1.25,
                                        letterSpacing: 0.24,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                              Expanded(
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    SizedBox(width: 24, height: 24, child: const Icon(Icons.calendar_today_outlined)),
                                    // Lỗi 3: Thêm SizedBox để tạo khoảng cách
                                    const SizedBox(height: 6),
                                    const Text(
                                      'Điều Trị',
                                      style: TextStyle(
                                        color: Colors.black,
                                        fontSize: 12,
                                        fontFamily: 'Urbanist',
                                        fontWeight: FontWeight.w600,
                                        height: 1.25,
                                        letterSpacing: 0.24,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                              Expanded(
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    SizedBox(width: 24, height: 24, child: const Icon(Icons.sync_alt_outlined)),
                                    // Lỗi 3: Thêm SizedBox để tạo khoảng cách
                                    const SizedBox(height: 6),
                                    const Text(
                                      'Tương tác',
                                      style: TextStyle(
                                        color: Colors.black,
                                        fontSize: 12,
                                        fontFamily: 'Urbanist',
                                        fontWeight: FontWeight.w500,
                                        height: 1.25,
                                        letterSpacing: 0.24,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}